### ISSUE TITLE
Mapping problem

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-standard#8]
When I have opened up the install tool in plain system I got the critical error ```No mapping information to process``` caused by Doctrine. I have removed the ```orm``` group from configuration and it worked. Not sure if a bug?

https://github.com/terminal42/contao-standard/blob/master/app/config/config.yml#L63

**Comment by aschempp** [comment]
That is a known limitation, you must have entities if you have ORM.

**Comment by qzminski** [comment]
That's by default in this repository which I think is not a very common case, shall we maybe drop it?

**Comment by aschempp** [comment]
I know… I thought it would be easier to remove features you don't need than figure out how Doctrine should be configured 😂

**Comment by qzminski** [comment]
Unless you have no idea about those features... I spent quite a few minutes figuring out what's wrong. Then maybe we should just comment it out or point it out in the readme?

**Comment by Toflar** [comment]
Guys, there's a wonderful thing that's called "comments" ;)

**Comment by Toflar** [comment]
> Then maybe we should just comment it out

👍

**Comment by aschempp** [comment]
Or we just use different branches :-)

**Comment by qzminski** [comment]
That's also possible. I just think that the regular version should run out of the box and not throw errors immediately ;-)

**Comment by Toflar** [comment]
I think multiple branches just increase the complexity and maintenance efforts...just comment that out, that's enough.

**Comment by aschempp** [comment]
fine for me

**Comment by qzminski** [comment]
Changed in 2ea5304.
